### ISSUE TITLE
管理者登入頁面 reset 按鈕 bug

### ISSUE THREAD

**Issue by ttnppedr** [ttnppedr/gipay#22]
bug 重製步驟
1. 輸入完帳號密碼後按下 reset 
2. focus 回帳號輸入框後輸入一個字
3. 密碼會自動出現並沒有被清空

@askiebaby 再麻煩檢查一下，感謝

**Comment by ttnppedr** [comment]
反之操作也有會 bug
focus 回密碼輸入框，帳號會自動出現

**Comment by askiebaby** [comment]
@ttnppedr 
1. `input[type="reset"]` 元素的預設行為就是將你已經輸入的內容清空，恢復成預設值（`[value="you-defalut"]`），`value` 沒設定就是清空，[詳見這篇 w3org spec](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion)。
2. focus 回帳號輸入框輸入一個字，會出現帳號可選，是因為瀏覽器有個密碼管理員（[詳見這篇 MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion)），在當初登入成功後，瀏覽器會詢問是否紀錄，而使用者同意後就會記錄起來，供下次登入使用。
3. 可以做到的是：
  - 防止舊版瀏覽器的 cache（`autocomplete="off"`）
  - 在刷新畫面時，隱藏已經記住的帳號密碼，在 focus 時才可以選擇記住的帳號密碼（透過 `readonly`）。
